### ISSUE TITLE
Remove old abbr

### ISSUE THREAD

**Issue by BarbzYHOOL** [jhillyerd/plugin-git#14]
No way to remove old abbr easily? :)

If we modify one, then we're left with two abbr doing the same thing

**Comment by jhillyerd** [comment]
Which ones in particular?  I want to preserve compatibility with https://github.com/robbyrussell/oh-my-zsh/wiki/Cheatsheet for the most part.  I'm OK with the commands working slightly different, but I don't want to remove abbrevs people may have memorized.

**Comment by BarbzYHOOL** [comment]
I'm just asking for custom usage then.

I modified gco to gch but I still have gco (for example), do I have to track each abbr and remove it 1 by 1?

**Comment by jhillyerd** [comment]
I don't think fish abbreviations are permanent, so if you log all the way out (or reboot), you should get just the ones present in your branch.  I could be wrong, I don't track fish development super closely.

**Comment by BarbzYHOOL** [comment]
nop I got both :(
