### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by Nyxelio** [jhillyerd/plugin-git#37]
Thanks for your awesome work.
I try to install your plugin on a fish fresh install (compiled from sources, version 3.1.0) but it fails on each line:
`__git.plugin_abbr: command not found`

Am I missing something ?
Thanks

**Comment by MartinDelille** [comment]
Maybe you can try to install it with a plugin manager like [fisher](https://github.com/jorgebucaran/fisher) ? 

```
fisher add jhillyerd/plugin-git
```

**Comment by Nyxelio** [comment]
Thanks ! This works like a charm.

**Comment by jhillyerd** [comment]
Playing around a bit, I was able to reproduce this, but not reliably.  I got the following for each abbr:

```
__git.plugin_abbr: command not found
~/.local/share/omf/pkg/git/init.fish (line 129):
__git.plugin_abbr gfp        git flow publish
^
from sourcing file ~/.local/share/omf/pkg/git/init.fish
        called on line 1 of file ~/.local/share/omf/pkg/git/hooks/install.fish

from sourcing file ~/.local/share/omf/pkg/git/hooks/install.fish
        called on line 8 of file ~/.local/share/omf/pkg/omf/functions/packages/omf.packages.run_hook.fish

in function “omf.packages.run_hook”
        called on line 74 of file ~/.local/share/omf/pkg/omf/functions/packages/omf.packages.install.fish
        with parameter list “/home/james/.local/share/omf/pkg/git install”

in function “omf.packages.install”
        called on line 14 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.install.fish
        with parameter list “https://github.com/jhillyerd/plugin-git”

in function “omf.cli.install”
        called on line 3 of file -
        with parameter list “https://github.com/jhillyerd/plugin-git”

in function “__omf_last_command”
        called on line 51 of file ~/.local/share/omf/pkg/omf/functions/omf.fish

in function “omf”
        called on standard input
        with parameter list “install https://github.com/jhillyerd/plugin-git”
```

I suspect there is a race condition with fish discovering functions defined in the `functions` directory. I suggest we create ` __git.plugin_abbr` at the top of init.fish, and erase it at the end.

**Comment by jhillyerd** [comment]
cc @NovaDev94

**Comment by kimnh-0823** [comment]
> Maybe you can try to install it with a plugin manager like [fisher](https://github.com/jorgebucaran/fisher) ?
> 
> ```
> fisher add jhillyerd/plugin-git
> ```

Athough I tried to install plugin-git successfully, it still does not work.
```bash
Command 'gst' not found, but can be installed with:                                                                                                                                                                                                                                                                                                                                                                                                                                             sudo apt install gnu-smalltalk
```

I am working on Ubuntu 18.04 WSL Terminal. Do you have any ideas?

**Comment by jhillyerd** [comment]
> Athough I tried to install plugin-git successfully, it still does not work.

If you run `abbr` you should be able to to see if it defined any abbreviations, I'm guess not in this case.

Can you try uninstalling and re-installing?  They may trigger a working install.

If still not working, can you let us know if you are using omf or fisher?  Do you get any errors?

**Comment by NovaDev94** [comment]
@jhillyerd I think I get what's wrong, since `__git.plugin_abbr` is stored in a separate function file. And it only gets included in the function path AFTER the plugin is installed successfully.

The problem is currently I'm sourcing the `init.fish` file in `hooks/install.fish` - which `__git.plugin_abbr` isn't around when it happens.

Let me make a patch.

**Comment by NovaDev94** [comment]
Patch submitted, I'm sorry for all the inconvenience caused.

**Comment by jhillyerd** [comment]
Thanks!
