### ISSUE TITLE
List all available git abbreviations and functions

### ISSUE THREAD

**Issue by wenjoy** [jhillyerd/plugin-git#40]
Per title, I cant remember so many shorthand command, I want to list them all in case I cant rember them.

Any suggestion?

**Comment by jhillyerd** [comment]
There isn't a way, but this is something I've wanted as well.  Now that we have our own function for adding abbreviations, we could also have it generate some sort of online documentation.

In the meantime, what I'd recommend is memorizing the common command roots: gb for branches, gc for commits, gd for diff, gl for log, etc.  Then you can just gc<tab> to start listing available commit commands.

**Comment by cmoesel** [comment]
For what it's worth, I'm new to fish, omf, and this plugin (and loving it) but would also really benefit from a feature like this.  So, if you're taking votes, count me in!

**Comment by pibebtol** [comment]
This is actually there.
Since this plugin uses `abbr` to create the abbreviations, you can just call:
`abbr -s` which lists all currently active abbreviations in the session.
Conveniently combine it with grep or fzf:
`abbr -s | grep commit` or `abbr -s | fzf` for filtering 👌
