### ISSUE TITLE
Please add confirmation for glcean!!!!

### ISSUE THREAD

**Issue by wenjoy** [jhillyerd/plugin-git#41]
I just ruined all my work of this afternoon with this command!!!!
It's a dangerous command to clean all your working tree and staged file, but its name looks like a `git clean`.

**Comment by jhillyerd** [comment]
Perhaps we should move `gclean` to `gclean!` and make `gclean` an abbreviation for the regular `git clean`, I agree that would be surprising.

**Comment by wenjoy** [comment]
I'd like to have a try.
