### ISSUE TITLE
Printing branches and their age.

### ISSUE THREAD

**Issue by axeII** [jhillyerd/plugin-git#43]
Found this command on the stackoverlflow : 
`git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'
`

Outpu example:
![](https://i.imgur.com/tDCTiZx.png)

which shows all branches and their age. I find this very useful. Can we have this in this tool as well? 🙏🏻 

Thanks.

**Comment by MartinDelille** [comment]
I'm experiencing it and I love it! thanks for the tip!
