### ISSUE TITLE
Not all abbreviations working when installed with fisher v4.1.0

### ISSUE THREAD

**Issue by bulkan** [jhillyerd/plugin-git#47]
Using `fisher v4.1.0` & `fish `3.1.2` not all abbreviations are available.

I'm assuming it has something to do with the [even-system](https://github.com/jorgebucaran/fisher#event-system)

**Comment by jhillyerd** [comment]
Abbreviations are setup in https://github.com/jhillyerd/plugin-git/blob/master/init.fish

Functions too complex to be an abbreviation live in https://github.com/jhillyerd/plugin-git/tree/master/functions

Are you missing all of one of those groups?

**Comment by patrickfatrick** [comment]
I don't think this package is compatible with Fisher. Fisher puts files in the .config/fish directories to work with fish's autoloading system. Most of the aliases in this package are in an `init` file that oh-my-fish resolves when the shell starts up.

**Comment by bulkan** [comment]
I've recently had to do another dev setup and I've installed fisher v4.1.0. This used to work with `fisher v3.2.10`. 

I'm going to ahead and close this issue as its a problem with fisher :)

**Comment by jhillyerd** [comment]
Fisher does claim `Oh My Fish! plugin support.` in its README.  I'm reasonably confident this plugin has worked with fisher in the past, it was even recommended in #37

**Comment by patrickfatrick** [comment]
I came across this from 2018 https://github.com/jorgebucaran/fisher/issues/481 which does indicate specifically call out `init.fish` as supported but it also seems to be quite ambivalent about supporting oh-my-fish plugins, so it's possible that may have changed since the.

**Comment by patrickfatrick** [comment]
Confirmed this was removed in Fisher 4.x https://github.com/jorgebucaran/fisher/releases/tag/4.0.0

**Comment by jhillyerd** [comment]
I opened #48 for this -- it would be nice to support both if possible.  Let us know if you find a clean way to do both @patrickfatrick
