### ISSUE TITLE
Fall back to main when master branch not found

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/plugin-git#50]
Many teams and tools (including GitHub) are shifting from `master` to `main` for the default branch.  This will break some of our commands, including: glom, grbm*, gcom, etc.

Git itself has no notion of a default branch, so there is no universal way to query for it.  Most online references suggest checking the fetch HEAD of the origin repo, but this makes the assumptions that there is a remote repo, and that it's called `origin`.

For commands that need to reference the default branch, given the prevalence of `master`, I think it makes sense to check if it exists first, and fall back to `main` if it does not.  This logic should be placed in a function that could later cache the value for a specific repo.

**Comment by y1zhou** [comment]
I haven't scripted in fish that much, but would something like this work?

```fish
function gcom -d "checkout master and fall back to main"
  if test (git branch --format '%(refname:short)' | grep -c '^master$') -eq 0
    git checkout master
  else
    git checkout main
  end
end
```

Of course this doesn't cache the default branch somewhere like you mentioned. I'm not sure where you'd want that to happen -- maintain a variable that keeps track of everything, or have a hidden file somewhere that logs this? Not sure how much more efficient this is gonna be compared to running `git branch` again.

**Comment by jhillyerd** [comment]
It's likely we can find a way to replace grep with fish's `string match`.  I'm OK with the initial version not doing any caching, but I'd prefer we put this into a function that can be called anywhere we need it for consistency.

**Comment by MartinDelille** [comment]
Here is the logic used by *Oh My Zsh* to retrieve the main branch: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh#L32-L43

**Comment by y1zhou** [comment]
Thanks @MartinDelille! In our case if we only care about checking for master and falling back to main, then it could be as simple as this:

```fish
function git_default_branch -d "Fallback to main when master branch is not found"
  # Silently fail when not in git directory
  command git rev-parse --git-dir &>/dev/null; or return
  if command git show-ref -q --verify refs/heads/master
    echo master
  else
    echo main
  end
end
```

With this the other functions like `gcom` could just call `git checkout (git_default_branch)`. Should this be added to `__git.init.fish`, or should we place this in a separate file? I'm not familiar with the layout of fish projects.

**Comment by jhillyerd** [comment]
I'd prefer it in it's own file similar to `__git.current_branch.fish` -- otherwise we impact fish's startup time.
