### ISSUE TITLE
How to disable/unalias commands?

### ISSUE THREAD

**Issue by p12y** [jhillyerd/plugin-git#55]
Thanks for the great plugin! Is there a way to disable some commands? It's interfering with GraphicsMagick which uses the command `gm`.

**Comment by p12y** [comment]
`abbr --erase WORD...`

**Comment by jhillyerd** [comment]
Yes, that should work -- we currently add the abbreviations once during installation, and let fish persist them between restarts.  So erasing one should also persist.

In case anyone lands on this bug, some other options:

Running with a path (ie /usr/bin/gm) or using the `command` built-in will bypass the abbreviation system.  I don't know how much you use graphics magick, but git merge is pretty core to most development workflows, so I expect daily users would prefer the abbreviation.
