### ISSUE TITLE
Switch back to "gb" for "git branch"?

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/plugin-git#6]
I have been considering switching back to `gb` for `git branch`, as I find `gbr` annoying to type.

My reason for using `gbr` was so that it didn't conflict with a (now defunct?) go build tool: https://github.com/constabulary/gb

Thoughts?

**Comment by RomainLanz** [comment]
Go for it 👍

**Comment by jhillyerd** [comment]
Not sure how far I want to stray from the [zsh plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh), will have to think on some of the other suggestions.   I noticed [someone else had a branch](https://github.com/jhillyerd/plugin-git/compare/master...johnpark82:master) with some similar changes to what you suggest.
