### ISSUE TITLE
Add to omf plugin repository

### ISSUE THREAD

**Issue by somebody1234** [jhillyerd/plugin-git#7]
Would you mind adding this [here](https://github.com/oh-my-fish/packages-main)?

**Comment by jhillyerd** [comment]
When I first created the package, I tried to get it included as an official omf plugin, but it was rejected.  I don't remember the exact reason, but I think it was to do with it mostly being a pile of aliases and not really doing anything.  I can try again.

**Comment by somebody1234** [comment]
Hmm, I got my zypper aliases merged in recently so it _should_ be okay now?

**Comment by jhillyerd** [comment]
Looks like they regularly reject git alias plugins: https://github.com/oh-my-fish/packages-main/pull/37
