### ISSUE TITLE
__git.current_branch returns branch name and branch head commit id

### ISSUE THREAD

**Issue by TheFehr** [jhillyerd/plugin-git#71]
I installed the plugin via omf and tried to use gpu (ggp --set-upstream) but it throws an error due to 'origin/36fafe7' not being resolved to a branch.

I then ran __git.current_branch directly and it returned my branch name as well as the commit id of the head.

If there is any more info I can offer to help solve this please let me know.

**Comment by jhillyerd** [comment]
Can you provide a repo (or steps to create one) that exhibits this issue?  Will make it much easier to troubleshoot.

**Comment by TheFehr** [comment]
The repo I encountered that was a private one from work. Will see if one of my public ones have the same problem.

**Comment by TheFehr** [comment]
So I checked quickly and I have the exact same behaviour with my-zivi/my-zivi

**Comment by TheFehr** [comment]
I am not sure if it has anything to do with a specific repository, because cloning this one and then executing 
```
__git.current_branch
```
returns 
```
master
2df7fe2
```

**Comment by TheFehr** [comment]
I found the error. The file had \r\n line endings
