### ISSUE TITLE
Rebasing on origin master would be nice

### ISSUE THREAD

**Issue by torhovland** [jhillyerd/plugin-git#75]
```
git fetch origin (__git.default_branch); and git rebase origin/(__git.default_branch)
```

**Comment by torhovland** [comment]
Good point. The last part is `grbom` there. For the first part, I suppose the user will do `gfo (__git.default_branch)` or simply `gfo`, `gfa` or `gf`.

I see there is a discussion on https://github.com/ohmyzsh/ohmyzsh/pull/8988

This one would be even nicer, as it does everything in one command, but it hasn't been merged: https://github.com/ohmyzsh/ohmyzsh/pull/10261

**Comment by jmeridth** [comment]
Could you get this with `gpr origin master`? [alias here](https://github.com/ohmyzsh/ohmyzsh/blob/dfee71c7735b739d6db478b2353752aeb6bc1ae2/plugins/git/git.plugin.zsh#L240)

**Comment by jhillyerd** [comment]
I believe #91 resolved this.
