### ISSUE TITLE
Not working under fisher anymore

### ISSUE THREAD

**Issue by eoli3n** [jhillyerd/plugin-git#78]
```bash
$ fish --version
fish, version 3.3.1

$ fisher --version
fisher, version 4.3.1
```

[![asciicast](https://asciinema.org/a/t4y09SNAI3cDzFbzKCtLkPXvO.svg)](https://asciinema.org/a/t4y09SNAI3cDzFbzKCtLkPXvO)

**Comment by jhillyerd** [comment]
I'm not a fisher user myself, so someone else will need to troubleshoot this.  As a workaround, you can try running `__git.init` manually, which should install the abbreviations.  You should only need to do this one time, and they will stick around for all new fish sessions.

**Comment by eoli3n** [comment]
Ok, just retried at home on Void Linux. It doesn't work on Arch Linux, but it still works on Void Linux.
So the problem seems to not be related to fisher.
Same fish and fisher versions on both OS.

If I manually run ``__git.init``, it works for the current shell.

**Comment by eoli3n** [comment]
I just removed then readd the plugin with fisher. It works perfectly.
No clue about what happened, but I can't reproduce. I will reopen if needed.
