### ISSUE TITLE
Checkout changes

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/plugin-git#8]
@RomainLanz had some suggestions in #6  including `gcob` for `git checkout -b`.  I've also seen a fork if this repo that used `gcom` and `gcod` for checking out `master` and `develop` branches; which I like.

This would also free up `gcm` to replace `gcmsg`

Comments or objections?

**Comment by RomainLanz** [comment]
I believe `gcom` and `gcod` are overkill since branch name are dynamic.

**Comment by jhillyerd** [comment]
I have a feeling you are in the minority there :)   I don't see any public statistics on branch naming, although it's likely it could be gathered from the GitHub BigQuery dataset.

I know master is very very very common; and I use `gcm` several times a day when coding.  I feel like develop is a good one because it is default in git-flow.  Most of my projects use develop, even if I am not using git flow.

**Comment by RomainLanz** [comment]
> I have a feeling you are in the minority there :)

Probably, but what I mean is that it's still a variable but it doesn't really matter after all 😄

**Comment by jhillyerd** [comment]
094c2347328a1f199a08f3a6f8c289dd68b92910

Next up; gcm

**Comment by jhillyerd** [comment]
gcm in fd07b593df09cc6e854c9c358193f05df433e4af
