### ISSUE TITLE
Add aliases for 'git worktree'

### ISSUE THREAD

**Issue by jayp0521** [jhillyerd/plugin-git#81]
Hello,

I was wondering what your thought is on creating similar aliases from oh my zsh for git worktree

https://github.com/ohmyzsh/ohmyzsh/pull/10079

**Comment by jhillyerd** [comment]
Looks good to me!

**Comment by jayp0521** [comment]
https://github.com/jhillyerd/plugin-git/pull/82

**Comment by jayp0521** [comment]
@jhillyerd should be good to go

**Comment by jhillyerd** [comment]
Looks good, thx.
