### ISSUE TITLE
Abbreviations do not work after restart with fish 3.6.0

### ISSUE THREAD

**Issue by niklasnatter** [jhillyerd/plugin-git#90]
Hey,
first of all - thanks a lot working on this plugin. I switched to fish from oh-my-zsh a few months ago and this plugin was a lifesaver!

I just set up a new machine today and installed the plugin with fisher:
```
fisher install jhillyerd/plugin-git
```

Unfortunately, it looks like the abbreviations of the plugin do not work anymore after i restart my machine.
I reinstalled the plugin, but this only solved the problem until the next restart.

I suspect that this is related to the changes to `abbr` that come with [fish 3.6.0](https://github.com/fish-shell/fish-shell/releases/tag/3.6.0). Is there a trick/workaround to make the plugin compatible with fish 3.6.0?

Thanks a lot in advance!

**Comment by niklasnatter** [comment]
I just found a potential workaround in https://github.com/jorgebucaran/fisher/issues/755#issuecomment-1408547461. Adding the following lines to my `~/.config/fish/config.fish` fixed the problem in a first test:
```
set -e __git_plugin_initialized
__git.init
```

**Comment by jhillyerd** [comment]
Yes, that looks like a good workaround.  #88 was a first look at fixing this, but appears to have stalled.  I'll take a deeper look, probably this week.

**Comment by lecovi** [comment]
Yes! It worked for me too.
