### ISSUE TITLE
Some aliases are not expanded automatically

### ISSUE THREAD

**Issue by niklasnatter** [jhillyerd/plugin-git#97]
Hey, 
thanks a lot for working on this plugin. It is part of my daily workflow and I would not want to miss it!

I noticed that some aliases (like `ggp`) are not expanded automatically when pressing enter/space. I dont know too much about fish yet, but by looking at the source code of the plugin i figured that this is because some aliases are implemented as function ([`ggp`](https://github.com/jhillyerd/plugin-git/blob/master/functions/ggp.fish), [`ggl`](https://github.com/jhillyerd/plugin-git/blob/master/functions/ggl.fish)) while others are implemented as abbreviations ([`gll`](https://github.com/jhillyerd/plugin-git/blob/master/functions/__git.init.fish#L152), [`gcom`](https://github.com/jhillyerd/plugin-git/blob/master/functions/__git.init.fish#L152)).

I really like the abbreviations functionality of fish because it allows me to easily check the full command behind the alias by pressing space. Is there a specific reason why some aliases are implemented as function?

Thanks a lot in advance!

**Comment by jhillyerd** [comment]
Yes, you are correct that functions are not expanded in the same way.  When I started the plugin, I only put bare git commands in the abbreviations, anything that relied on expanding the current or main branch names was a function.  That's probably not necessary for any of the one liners.  Some like grename and gtest are more complex and wouldn't work as an abbr.

If you are interested in migrating some of the simple ones back to abbr, I'd accept PRs for that.  Please test them, we do not have any automated testing.

**Comment by niklasnatter** [comment]
Hey, thanks for the fast response! I created a small pull request to adjust the simple aliases to use abbreviations: https://github.com/jhillyerd/plugin-git/pull/98
